// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Attachment
{
    public Guid Id { get; set; }

    public Guid MessageId { get; set; }

    public string FileUrl { get; set; }

    public string FileType { get; set; }

    public int FileSize { get; set; }

    public string Directory { get; set; }

    public virtual Message Message { get; set; }
}