// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Domain.Entities;

public partial class Friend
{
    public Guid Id { get; set; }

    public Guid UserId { get; set; }

    public Guid FriendId { get; set; }

    public string Status { get; set; }

    public DateTime CreatedOn { get; set; }

    public DateTime? UpdatedOn { get; set; }

    public virtual User FriendNavigation { get; set; }

    public virtual User User { get; set; }
}